//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exemple2
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int res_id { get; set; }
        public int res_cha_id { get; set; }
        public int res_cli_id { get; set; }
        public System.DateTime res_date { get; set; }
        public System.DateTime res_date_debut { get; set; }
        public System.DateTime res_date_fin { get; set; }
        public decimal res_prix { get; set; }
        public Nullable<decimal> res_arrhes { get; set; }
    
        public virtual chambre chambre { get; set; }
        public virtual client client { get; set; }
    }
}
